### PR TITLE
Handle dirs with file-like names

### PR DESCRIPTION
**Pull request by antongolub**

### CODE REVIEW

**Comment by antongolub** [comment]
Hey, @mothepro,

I've found your lib too late. Anyway, just FYI, your todos + some other corner cases are finally covered with this "yet-another-one" tsc-esm workaround.

**Comment by mothepro** [comment]
Woohoo!

Originally, I made `tsc-esm` for TypeScript ESM modules to be included directly into the browser with out any build configurations.
I forgot about the tsc-esm solution since shortly afterwards TSC left imports ending with `.js` alone. Meaning you can just write your typescript appending the js file extension with no external dependencies. However, this doesn’t seem to be the case with jest, which you fixed :)

**Comment by antongolub** [comment]
Aha, I think it's reasonable. "import everything with '.js'" is exactly what Sindre recommends in [ESM guide](https://github.com/sindresorhus/meta/discussions/15). Well, [with some minor tweaks](https://github.com/antongolub/tsc-esm-fix/pull/32/) this patcher may be applied just once to the entire ts-project. From now this is also a one-time ESM migration utility. Thanks for the advice!

**Pull request merged**
